### ISSUE TITLE
UI breaks on loading data from server on ios

### ISSUE THREAD

**Issue by mmueller301** [GSE-Project/SS2016-group2#82] opened 2016-06-13 10:40 UTC
Does this also happen on Android @themetalone? 
Need bug fixes

<img width="370" alt="bildschirmfoto 2016-06-13 um 12 38 22" src="https://cloud.githubusercontent.com/assets/18538843/16004755/cf0f7f70-3163-11e6-80ee-1330ee192b45.png">

**Comment by themetalone** [comment] 2016-06-13 10:46
Is this from the current development branch?

**Comment by themetalone** [comment] 2016-06-13 10:59
I simulated it with `ionic serve -t android` and the list is rendered as expected. But the console showed me some errors/warnings:

```
TypeScript error: C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/app/components/map/map.ts(5,9): Error TS2305: Module '"C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/node_modules/ionic-native/dist/index"' has no exported member 'GoogleMap'.
TypeScript error: C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/app/components/map/map.ts(5,20): Error TS2305: Module '"C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/node_modules/ionic-native/dist/index"' has no exported member 'GoogleMapsEvent'.
TypeScript error: C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/app/components/native-map/native-map.ts(5,9): Error TS2305: Module '"C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/node_modules/ionic-native/dist/index"' has no exported member 'GoogleMap'.
TypeScript error: C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/app/components/native-map/native-map.ts(5,20): Error TS2305: Module '"C:/Users/steff/Documents/Uni/GSE/Group2/CitizenApplication/node_modules/ionic-native/dist/index"' has no exported member 'GoogleMapsEvent'.
```

**Comment by skaldo** [comment] 2016-06-13 11:55
Hi @mmueller301, @themetalone. I'm aware of this issue, its problem only if the app runs in safari. It has been fixed in the version before Angular2 upgrade.

I'll take care of this one.

**Comment by skaldo** [comment] 2016-06-13 14:15
This was caused by the the old data in the LocalStorage. We are going to implement a feature that is going to prevent this from happening in the future. See #83.

**Closed by skaldo** 2016-06-13 14:15 UTC
Labels: active, bug, regression, systest
